apiVersion: v2
name: generic
description: A generic Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: latest
maintainers:
  - name: colearendt
    email: packages@arendt.life
    url: https://github.com/colearendt
