config:
  log-level: warn
  default-provider: oidc
  insecure-cookie: false

strategy: {}
replicas: 1
podAnnotations: {}
serviceAnnotations: {}

image:
  repository: thomseddon/traefik-forward-auth
  tag: 2
  pullPolicy: IfNotPresent

pod:
  env: {}
command:
  - './traefik-forward-auth'
args:
  - '--config=/config/config.ini'
resources: {}
livenessProbe: {}
startupProbe: {}
readinessProbe: {}
