apiVersion: v2
name: regcred
description: A Helm chart that deploys registry credential secrets

type: application
version: 0.1.0
appVersion: "0.1.0"

maintainers:
  - name: colearendt
    email: helm@colearendt.com
    url: https://github.com/colearendt
