# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

extraLabels: {}

registryCredentials: []
#   - url: ghcr.io
#     username: 'username'
#     password: 'password'
#
