apiVersion: v2
name: postgrest
description: A Helm chart for deploying Postgrest to Kubernetes
type: application
version: 0.1.1
appVersion: v8.0.0
maintainers:
  - name: colearendt
    email: helm@arendt.life
    url: https://github.com/colearendt
