{{- if .Values.registryCredentials -}}
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: {{ include "regcred.fullname" . }}
  labels:
    {{- include "regcred.labels" . | nindent 4}}
    {{- with .Values.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  .dockerconfigjson: {{- include "regcred.registryCredentials" .Values.registryCredentials | nindent 4 }}
{{- end -}}
