{{- if .Values.mountSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.fullname" . }}-secret-mount
  namespace: {{ $.Release.Namespace }}
stringData:
  {{- include "generic.config.configmap" (dict "context" $ "value" .Values.mountSecret ) | nindent 2 }}
{{- end }}
{{- if .Values.secretEnv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic.fullname" . }}-secret-env
  namespace: {{ $.Release.Namespace }}
stringData:
  {{- $global := $ }}
  {{- range $secret := .Values.secretEnv }}
    {{- if or (not (hasKey $secret "name" )) (not (hasKey $secret "value")) }}
      {{- fail "secretEnv entries require both a 'name' and a 'value' key" }}
    {{- end }}
    {{- printf "%s: |" (get $secret "name") | nindent 2 }}
    {{- include "generic.tplvalues.render" (dict "value" (get $secret "value") "context" $global) | nindent 4 }}
  {{- end }}
{{- end }}
