---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  config.ini: |
{{- range $key, $val := $.Values.config }}
    {{ $key }} = {{ $val }}
{{- end }}
---
