apiVersion: v2
name: training-ns
description: A Helm chart to help train users on Kubernetes
type: application
version: 0.0.1
appVersion: "0.0.1"
maintainers:
  - name: colearendt
    email: helm@arendt.life
    url: https://github.com/colearendt
