users:
  - test

namespacePrivileges:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"

clusterPrivileges:
  - apiGroups:
      - ""
    resources:
      - "nodes"
    verbs:
      - "get"
      - "list"
      - "watch"
