apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgrest.fullname" . }}-secret
  namespace: {{ $.Release.Namespace }}
stringData:
  db-uri.txt: |-
    {{- .Values.postgrest.dbUri | nindent 4 }}
  jwt-secret.txt: |-
    {{- .Values.postgrest.jwtSecret | nindent 4 }}
  {{- if .Values.secret }}
    {{- toYaml .Values.secret | nindent 2 }}
  {{- end }}
