extraObjects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "test"
    data:
      something: fun
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: "test2"
    data:
      something: {{ printf "fun2" }}
